kadiri_produits:
    resource: "@KadiriBundle/Resources/config/routing/produits.yml"
    prefix:   /produits

kadiri_homepage:
    path:     /
    defaults: { _controller: KadiriBundle:Default:index }

kadiri_medecin:
        resource: "@KadiriBundle/Resources/config/routing/medecin.yml"
        prefix:   /medecin

kadiri_commande:
        resource: "@KadiriBundle/Resources/config/routing/commande.yml"
        prefix:   /commande
