<?php

namespace Kadiri\KadiriBundle\Repository;

/**
 * ProduitsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function recherche($designation)
    {
        $qb = $this->createQueryBuilder('p')
              ;

        $qb
     ->where('p.designation like :designation')
     ->setParameter('designation', $designation)
      ;

        return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
