commande_index:
    path:     /
    defaults: { _controller: "KadiriBundle:commande:index" }
    methods:  GET

commande_show:
    path:     /{id}/show
    defaults: { _controller: "KadiriBundle:commande:show" }
    methods:  GET

commande_new:
    path:     /new
    defaults: { _controller: "KadiriBundle:commande:new" }
    methods:  [GET, POST]

commande_edit:
    path:     /{id}/edit
    defaults: { _controller: "KadiriBundle:commande:edit" }
    methods:  [GET, POST]

commande_delete:
    path:     /{id}/delete
    defaults: { _controller: "KadiriBundle:commande:delete" }
    methods:  DELETE
